// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package runner

import (
	"sync"

	"github.com/balerter/balerter/internal/script/script"
)

// scriptsManagerMock is a mock implementation of scriptsManager.
//
// 	func TestSomethingThatUsesscriptsManager(t *testing.T) {
//
// 		// make and configure a mocked scriptsManager
// 		mockedscriptsManager := &scriptsManagerMock{
// 			GetFunc: func() ([]*script.Script, error) {
// 				panic("mock out the Get method")
// 			},
// 		}
//
// 		// use mockedscriptsManager in code that requires scriptsManager
// 		// and then make assertions.
//
// 	}
type scriptsManagerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func() ([]*script.Script, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *scriptsManagerMock) Get() ([]*script.Script, error) {
	if mock.GetFunc == nil {
		panic("scriptsManagerMock.GetFunc: method is nil but scriptsManager.Get was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc()
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedscriptsManager.GetCalls())
func (mock *scriptsManagerMock) GetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
