name: main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@master

      - name: run tests
        run: |
          make test-full

      - name: Publish coverage
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt

      - name: docker login
        run: |
          echo ${{ secrets.NEGASUS_DOCKER_TOKEN }} | docker login --username negasus --password-stdin
          echo ${{ secrets.NEGASUS_PAT }} | docker login ghcr.io -u negasus --password-stdin

      - name: build and push dev version
        run: |
          make build-dev
          make push-dev
